// models/Message.js — Individual Message Schema
const mongoose = require('mongoose');

const messageSchema = new mongoose.Schema(
  {
    // Which chat session this message belongs to
    chat: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Chat',
      required: true,
    },
    // 'user' = human, 'assistant' = AI, 'system' = system prompt
    role: {
      type: String,
      enum: ['user', 'assistant', 'system'],
      required: true,
    },
    // The actual text content
    content: {
      type: String,
      required: true,
    },
    // Optional: file attachment metadata
    file: {
      originalName: String,
      storedName: String,
      mimetype: String,
      size: Number,
      url: String,
    },
    // Tokens consumed for this specific message pair
    tokens: {
      type: Number,
      default: 0,
    },
    // Was this message generated by a specific tool?
    tool: {
      type: String,
      enum: ['chat', 'summarize', 'code', 'qa', null],
      default: null,
    },
  },
  { timestamps: true }
);

// Compound index for efficient chat history retrieval
messageSchema.index({ chat: 1, createdAt: 1 });

module.exports = mongoose.model('Message', messageSchema);
